### ISSUE TITLE
line trimming interferes with `git status --porcelain`

### ISSUE THREAD

**Issue by jimlloyd** [JarvusInnovations/git-client#20]
I need to parse the output of `git status --porcelain`, in which leading spaces on the line are significant. The use of the method `trim()` removes spaces from both ends of the string, which corrupts the input before I can parse it.

**Comment by themightychris** [comment]
@jimlloyd thanks for the report! Have you experimented with removing it already? I'm wondering where there might be negative side effects of removing the default trimming or limiting it to trailing whitespace or even just newlines

Worst case, it might need to be an exec option to suppress it

**Comment by themightychris** [comment]
hey @jimlloyd I just ran into this and fixed it :-)
